### ISSUE TITLE
[Feature Request] In Cash segment delivery data

### ISSUE THREAD

**Issue by virresh** [virresh/nseeod#1]
Original comment for archival purposes:
``
One request - 1) If possible download all indexes data. 2)In Cash segment delivery data is downloaded in GetBhavcopy. If that can be added in "OpenInterest" column, which is marked "0" right now.
```


This looks like inconsistent behaviour to me. For e.g in only equities, the open interest is set to 0, whereas for other data open interest has some value. 
Probably this field needs to be added to all the sections?


Also I'm not sure what is meant by "all indexes data". Including BSE, NASDAQ etc?

If someone thinks this is worthwhile to add, I'd be happy to accept PRs (or discussion as well)

**Comment by kalyan4512** [comment]
thanx a lot for update the software. i think the software as it is now is ok ,sud not add more indices as it may slow down dnload. but if other wants u can add delivery data but not at the cost of destabilizing this app.  pls stay with us if some issue arise. it is the fastest downloader i think and u have done a great job. all index data means indices listed in nse cash but it may slow the download if good net is not there as in the case of getbhavcopy

**Comment by kalyan4512** [comment]
just adding one point , in previous version there was a bat file name "nseeoddatadownloader.bat" but in this version it is not there but it is working ok. just mention it

**Comment by virresh** [comment]
I see.
Thanks for reporting. Updated the release description.

Since getbhavcopy is already handling it, I won't add extra indices in favor of performance.

**Comment by kalyan4512** [comment]
till now without bat file working ok ,but as u say in some pc it may not work without this bat file is it?

**Comment by virresh** [comment]
Nope, that's not what I meant.

I work in Linux OSes (ex Ubuntu), where bat files have no meaning. bat files are just some convenience scripts (only for windows) to launch the jar file and thus are completely optional.

I have added the bat file just in case someone on Windows was using them as a convenience script. The program should run just fine without bat file.
